language: python
python:
    - "2.7"
    - "3.6"
env:
    - TOX_ENV=flake8,pylint
install:
    # Install kpet using pip to ensure dependencies are downloaded correctly.
    - pip install .[dev]
    - pip install coveralls tox
script:
    - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .) -e ${TOX_ENV}
    - pip uninstall -y kpet
